#! /bin/bash

IMAPUSER=example
CONTAINER_VOLUMES_DIR=${HOME}/docker_volumes/imapscan

mkdir ${CONTAINER_VOLUMES_DIR}/spamassassin 2>/dev/null
mkdir ${CONTAINER_VOLUMES_DIR}/accounts 2>/dev/null
mkdir ${CONTAINER_VOLUMES_DIR}/imapfilter 2>/dev/null

docker run -d --rm --name imapscan_${IMAPUSER} \
	-v ${CONTAINER_VOLUMES_DIR}/spamassassin:/var/spamassassin \
	-v ${CONTAINER_VOLUMES_DIR}/imapfilter:/root/.imapfilter \
	-v ${CONTAINER_VOLUMES_DIR}/accounts:/root/accounts \
	domcomte/imapscan:latest
