#! /bin/bash

cd /root
if [ ! -f startup_done ]; then
  if [ -f /var/spamassassin/scan_lock ]; then
    rm /var/spamassassin/scan_lock
  fi
  # move default config files to volumes if missing
  if [ ! -f /var/spamassassin/user_prefs ]; then
    mv spamassassin_user_prefs /var/spamassassin/user_prefs
  else
    rm spamassassin_user_prefs
  fi
  if [ ! -f /root/.spamassassin/user_prefs ]; then
    mkdir /root/.spamassassin
    cp /var/spamassassin/user_prefs /root/.spamassassin/user_prefs
  fi
  if [ ! -f .imapfilter/config.lua ]; then
    mv imapfilter_config.lua .imapfilter/config.lua
  else
    rm imapfilter_config.lua
  fi
  if [ ! -f accounts/imap_accounts.txt ]; then
    mv imap_accounts.txt accounts/imap_accounts.txt
  else
    rm imap_accounts.txt
  fi
  if [ ! -f accounts/imap_accounts_learn.txt ]; then
    cp accounts/imap_accounts.txt accounts/imap_accounts.txt
  fi

  unlink /etc/localtime
  ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
  unlink /etc/timezone
  ln -s /usr/share/zoneinfo/Europe/Paris /etc/timezone

  touch startup_done
fi

alias logger="logger -e -s"

# start services, etc...
logger "starting services"
service rsyslog start
service exim4 start
service dbus start

logger "updating SpamAssassin rules"
sa-update -v --refreshmirrors | logger
logger "running sa-learn"
sa-learn --force-expire | logger

logger "starting spamassassin"
service spamassassin start

logger "running learm_spam"
./learn_spam.sh | logger

logger "starting CRON"
service cron start
